name: Python CI

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  python-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Check Python Version
        run: python --version

      - name: Run Unit Tests
        run: pytest

  build-demo:          # 👈 NEW JOB
    runs-on: ubuntu-latest

    steps:
      - name: Build Job
        run: |
          echo "Running Build Job"
          sleep 10
          echo "Build Finished"